/// Flutter icons Rollbrett_Flutter
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Rollbrett_Flutter
///      fonts:
///       - asset: fonts/Rollbrett_Flutter.ttf
///
///
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'custom_icons';
  static const String _kFontPkg = null;

  static const IconData noun_half_pipe_699586 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skateboard = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_camera = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice = IconData(0xf522, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
